import pyvista as pv
import os

# --- Configuration ---
# Path to the specific VTK file generated by the 'surfaces' function object
# This is typically located in: data/<run_name>/saved_surfaces/<stage_name>/<surface_name>.vtp
vtk_file_path = "/home/ericy/Rocket_CFD_ML/data/Mesh_Fidelity_T7_HF_2/reference/saved_surfaces/01_potential/rocket_skin.vtp"

# --- Execution ---
if not os.path.exists(vtk_file_path):
    print(f"Error: File not found at {vtk_file_path}")
    print("Please check that the simulation ran with surface extraction enabled and the path is correct.")
else:
    print(f"Loading: {vtk_file_path}")
    
    # 1. Read the mesh using PyVista
    # PyVista is preferred over meshio here because it handles the VTK format natively 
    # and provides immediate access to visualization and data analysis tools.
    mesh = pv.read(vtk_file_path)
    # 2. Print Statistics
    print("-" * 30)
    print(f" Mesh Statistics")
    print("-" * 30)
    print(f" Number of Points: {mesh.n_points}")
    print(f" Number of Cells:  {mesh.n_cells}")
    
    # 3. Inspect Data Fields (p, U, T, etc.)
    print("-" * 30)
    print(f" Available Fields")
    print("-" * 30)
    print(f" Arrays: {mesh.array_names}")
    # Example: Print range of Pressure (p) if available
    if "p" in mesh.array_names:
        p_min, p_max = mesh["p"].min(), mesh["p"].max()
        print(f" Pressure (p):     Min={p_min:.2f}, Max={p_max:.2f}")
    # Example: Print range of Temperature (T) if available
    if "T" in mesh.array_names:
        t_min, t_max = mesh["T"].min(), mesh["T"].max()
        print(f" Temperature (T):  Min={t_min:.2f}, Max={t_max:.2f}")
